name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust according to your build script

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'  # Only deploy on push to master branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip project
        run: zip -r ${{secrets.APP_NAME}}.zip build public package.json yarn.lock version.txt

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          scp -r ./${{ secrets.APP_NAME }}.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/projects/archived
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sh projects/deploy.sh ${{ secrets.APP_NAME }}'  # Adjust according to your deployment process
