name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust according to your build script

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'  # Only deploy on push to master branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          scp -r ./dist ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/projects
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'pm2 restart all'  # Adjust according to your deployment process
